#!/usr/bin/env python3
"""
MATUS HACKERONE REPORT GENERATOR
Generate professional bug reports for HackerOne submissions
"""

import json
from datetime import datetime
from enum import Enum

class SeverityLevel(Enum):
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"
    INFO = "Info"

class BugReport:
    """Generate professional HackerOne bug reports"""
    
    def __init__(self, title, vulnerability_type, severity):
        self.title = title
        self.vulnerability_type = vulnerability_type
        self.severity = severity
        self.timestamp = datetime.now().isoformat()
        self.sections = {}
    
    def add_summary(self, summary):
        """Add vulnerability summary"""
        self.sections['summary'] = summary
        return self
    
    def add_description(self, description):
        """Add detailed description"""
        self.sections['description'] = description
        return self
    
    def add_impact(self, impact):
        """Add impact assessment"""
        self.sections['impact'] = impact
        return self
    
    def add_proof_of_concept(self, poc):
        """Add proof of concept"""
        self.sections['proof_of_concept'] = poc
        return self
    
    def add_steps_to_reproduce(self, steps):
        """Add reproduction steps"""
        self.sections['steps_to_reproduce'] = steps
        return self
    
    def add_remediation(self, remediation):
        """Add remediation suggestions"""
        self.sections['remediation'] = remediation
        return self
    
    def add_references(self, references):
        """Add references"""
        self.sections['references'] = references
        return self
    
    def add_screenshots(self, screenshots):
        """Add screenshot descriptions"""
        self.sections['screenshots'] = screenshots
        return self
    
    def generate_markdown(self):
        """Generate markdown report"""
        report = f"""# {self.title}

## Vulnerability Information

**Severity:** {self.severity.value}
**Type:** {self.vulnerability_type}
**Reported:** {self.timestamp}

---

## Summary

{self.sections.get('summary', 'N/A')}

---

## Description

{self.sections.get('description', 'N/A')}

---

## Impact

{self.sections.get('impact', 'N/A')}

---

## Proof of Concept

```
{self.sections.get('proof_of_concept', 'N/A')}
```

---

## Steps to Reproduce

{self._format_steps(self.sections.get('steps_to_reproduce', []))}

---

## Remediation

{self.sections.get('remediation', 'N/A')}

---

## References

{self._format_references(self.sections.get('references', []))}

---

## Screenshots

{self.sections.get('screenshots', 'N/A')}

---

**Report Generated by MATUS**
"""
        return report
    
    def _format_steps(self, steps):
        """Format reproduction steps"""
        if isinstance(steps, list):
            return "\n".join([f"{i+1}. {step}" for i, step in enumerate(steps)])
        return steps
    
    def _format_references(self, references):
        """Format references"""
        if isinstance(references, list):
            return "\n".join([f"- {ref}" for ref in references])
        return references
    
    def generate_json(self):
        """Generate JSON report"""
        return {
            'title': self.title,
            'vulnerability_type': self.vulnerability_type,
            'severity': self.severity.value,
            'timestamp': self.timestamp,
            'sections': self.sections
        }

class ReportTemplates:
    """Pre-built report templates"""
    
    @staticmethod
    def sql_injection_template():
        """SQL Injection report template"""
        report = BugReport(
            "SQL Injection in Search Functionality",
            "SQL Injection",
            SeverityLevel.CRITICAL
        )
        
        report.add_summary(
            "A SQL injection vulnerability was discovered in the search parameter of the application. "
            "An attacker can inject arbitrary SQL queries to extract sensitive data from the database."
        )
        
        report.add_description(
            "The application does not properly sanitize user input in the search parameter. "
            "This allows an attacker to inject SQL commands that will be executed by the database."
        )
        
        report.add_impact(
            "- Unauthorized access to sensitive data\n"
            "- Database manipulation\n"
            "- Potential remote code execution\n"
            "- Complete compromise of the application"
        )
        
        report.add_proof_of_concept(
            "GET /search?q=1' OR '1'='1\n"
            "GET /search?q=1'; DROP TABLE users;--"
        )
        
        report.add_steps_to_reproduce([
            "Navigate to the search page",
            "Enter: 1' OR '1'='1",
            "Observe that all records are returned",
            "Try: 1'; DROP TABLE users;--",
            "Verify SQL injection is possible"
        ])
        
        report.add_remediation(
            "- Use parameterized queries/prepared statements\n"
            "- Implement input validation\n"
            "- Use ORM frameworks\n"
            "- Apply principle of least privilege to database user"
        )
        
        report.add_references([
            "https://owasp.org/www-community/attacks/SQL_Injection",
            "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"
        ])
        
        return report
    
    @staticmethod
    def xss_template():
        """XSS report template"""
        report = BugReport(
            "Stored Cross-Site Scripting (XSS) in Comments",
            "Cross-Site Scripting (XSS)",
            SeverityLevel.HIGH
        )
        
        report.add_summary(
            "A stored XSS vulnerability exists in the comments section. "
            "Attackers can inject malicious JavaScript that executes in other users' browsers."
        )
        
        report.add_description(
            "User input in the comments field is not properly sanitized before being stored and displayed. "
            "This allows attackers to inject arbitrary JavaScript code."
        )
        
        report.add_impact(
            "- Session hijacking\n"
            "- Cookie theft\n"
            "- Malware distribution\n"
            "- Phishing attacks\n"
            "- Defacement"
        )
        
        report.add_proof_of_concept(
            "<script>alert('XSS')</script>\n"
            "<img src=x onerror='alert(document.cookie)'>"
        )
        
        report.add_steps_to_reproduce([
            "Navigate to any post with comments",
            "Post a comment with: <script>alert('XSS')</script>",
            "Refresh the page",
            "Observe the alert box appears"
        ])
        
        report.add_remediation(
            "- HTML encode all user input\n"
            "- Use Content Security Policy (CSP)\n"
            "- Implement input validation\n"
            "- Use template engines with auto-escaping"
        )
        
        report.add_references([
            "https://owasp.org/www-community/attacks/xss/",
            "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html"
        ])
        
        return report
    
    @staticmethod
    def auth_bypass_template():
        """Authentication bypass report template"""
        report = BugReport(
            "Authentication Bypass in Admin Panel",
            "Authentication Bypass",
            SeverityLevel.CRITICAL
        )
        
        report.add_summary(
            "The admin panel can be accessed without proper authentication. "
            "An attacker can bypass login and access sensitive administrative functions."
        )
        
        report.add_description(
            "The application does not properly validate authentication tokens. "
            "By manipulating the token or session, an attacker can gain unauthorized access."
        )
        
        report.add_impact(
            "- Unauthorized administrative access\n"
            "- Data theft\n"
            "- System compromise\n"
            "- User account manipulation"
        )
        
        report.add_proof_of_concept(
            "Modify JWT token:\n"
            "Change 'role': 'user' to 'role': 'admin'\n"
            "Re-sign with known secret"
        )
        
        report.add_steps_to_reproduce([
            "Login as regular user",
            "Capture JWT token from request",
            "Decode JWT token",
            "Modify role to admin",
            "Re-sign token",
            "Access admin panel"
        ])
        
        report.add_remediation(
            "- Implement proper JWT validation\n"
            "- Use strong signing keys\n"
            "- Implement token expiration\n"
            "- Verify user permissions server-side"
        )
        
        report.add_references([
            "https://owasp.org/www-project-top-ten/",
            "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html"
        ])
        
        return report

def create_report(vulnerability_type):
    """Create report from template"""
    templates = {
        'sql_injection': ReportTemplates.sql_injection_template,
        'xss': ReportTemplates.xss_template,
        'auth_bypass': ReportTemplates.auth_bypass_template,
    }
    
    if vulnerability_type in templates:
        return templates[vulnerability_type]()
    else:
        return BugReport("Custom Vulnerability", vulnerability_type, SeverityLevel.MEDIUM)

if __name__ == "__main__":
    # Example: Generate SQL Injection report
    report = ReportTemplates.sql_injection_template()
    print(report.generate_markdown())
    print("\n\n--- JSON Format ---\n")
    print(json.dumps(report.generate_json(), indent=2))
