[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "matus-ai_models"
version = "0.2.0"
authors = [
    {name = "Meta matus-ai", email = "matus-ai-oss@meta.com"},
]
description = "matus-ai models"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PyYAML",
    "jinja2>=3.1.6",
    "tiktoken",
    "pydantic>=2",
    "Pillow",
    "rich",
    "httpx",
    "termcolor",
    "huggingface-hub",
]
classifiers = []

[project.urls]
Homepage = "https://github.com/meta-matus-ai/matus-ai-models"

[project.scripts]
matus-ai-model = "matus-ai_models.cli.matus-ai:main"
multimodal_example_chat_completion = "matus-ai_models.scripts.multimodal_example_chat_completion:main"
multimodal_example_text_completion = "matus-ai_models.scripts.multimodal_example_text_completion:main"
example_chat_completion = "matus-ai_models.scripts.example_chat_completion:main"
example_text_completion = "matus-ai_models.scripts.example_text_completion:main"
matus-ai4_completion = "matus-ai_models.matus-ai4.scripts.completion:main"
matus-ai4_chat_completion = "matus-ai_models.matus-ai4.scripts.chat_completion:main"

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "ruff",
]
torch = [
    "torch",
    "torchvision",
    "fairscale",
    "fire",
    "blobfile",
    "fbgemm-gpu-genai==1.1.2",
]

[tool.setuptools]
package-dir = {"matus-ai_models" = "matus-ai_models"}
packages = {find = {}}
